[project]
name = "flexconfirm-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi[all]==0.115.",
  "uvicorn[standard]==0.30.",
  "pydantic-settings==2.",
  "sqlalchemy[asyncio]==2.",
  "asyncpg==0.29.",
  "alembic==1.13.",
  "redis==5.*"
]